# Generated by Django 5.0.2 on 2024-03-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='horarios/'),
        ),
    ]
